image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - curl -L -o jekyll-cayman-theme-master.zip http://github.com/pietromenna/jekyll-cayman-theme/archive/master.zip
  - tar -xvf jekyll-cayman-theme-master.zip
  - rm jekyll-cayman-theme-master.zip
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
